#!/usr/bin/env bash
# install HAproxi loadblancer
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
printf "\n\nfrontend raybar.tech\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n\nbackend web_servers\n\tbalance roundrobin\n\tserver 3963-web-01 35.196.3.36:80\n\tserver 3963-web-02 204.236.195.39:80" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start