#!/usr/bin/env bash
# configures an Ubuntu server with
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
if grep -q "facebook.com" ~/hosts.new
then
	sed -i 's/8.8.8.8/facebook.com/g' ~/hosts.new
else
	echo "8.8.8.8 facebook.com" >> ~/hosts.new
fi
cp -f ~/hosts.new /etc/hosts
